apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app-deployment
  labels:
    app: my-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
      - name: my-devops-app
        image: mosala7320/my-devops-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"